version: "3.9"
services:
    mysqldb:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password@123
            MYSQL_DATABASE: testvals
        ports:
            - "8001:3306"
        volumes:
            - ./seed:/docker-entrypoint-initdb.d
    api:
        restart: always
        build:
            context: .
            dockerfile: api/Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - mysqldb
        environment:
            DB_PORT: 8001
            DB_HOSTNAME: mysqldb
            DB_USERNAME: root
            DB_DATABASE: testvals
            DB_PASSWORD: password@123
    workers:
        restart: always
        build:
            context: .
            dockerfile: workers/Dockerfile
        depends_on:
            - mysqldb
        environment:
            DB_PORT: 8001
            DB_HOSTNAME: mysqldb
            DB_USERNAME: root
            DB_DATABASE: testvals
            DB_PASSWORD: password@123